# Generated by Django 4.2 on 2023-04-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RR_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rr_id', models.IntegerField(unique=True)),
                ('user_hash', models.CharField(max_length=256, unique=True)),
            ],
        ),
    ]
