# Generated by Django 4.2 on 2023-04-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='status_code',
            field=models.CharField(choices=[('NW', 'New'), ('AC', 'Accepted'), ('RJ', 'Rejected')], default='NW', max_length=2),
        ),
    ]
